const questions=[
 {key:'cloud',text:'Do you work in Cloud?',opts:['Yes','No']},
 {key:'customer',text:'Do you work in Customer Relations? (CSAM, CSM, Customer Service, B2B, B2C, SDR, Sales Representative, etc.)',opts:['Yes','No']},
 {key:'english',text:'Do you speak English?',opts:['Yes','No']},
 {key:'language',text:'Do you speak Portuguese or Norwegian?',opts:['Portuguese','Norwegian','Both','Neither']},
 {key:'family',text:'Are you migrating with your family?',opts:['Yes','No']},
 {key:'securitySalary',text:'Which is more important to you: “Security” or “a good salary”?',opts:['Security','A good salary']},
 {key:'salaryJobs',text:'Which is more important to you: “an excellent salary” or “better job opportunities”?',opts:['Excellent salary','Better job opportunities']}
];
const data={Canada:{w:12.87,u:.067,tech:.14,cr:.05,peace:14},Australia:{w:18,u:.045,tech:.15,cr:.051,peace:20},'New Zealand':{w:14.02,u:.05,tech:.15,cr:.05,peace:2},Brazil:{w:10.13,u:.054,tech:.16,cr:.049,peace:124},Norway:{w:20.10,u:.046,tech:.14,cr:.05,peace:33}};
let step=0,answers={};const messages=document.getElementById('messages'),options=document.getElementById('options');
function bubble(role,text){const row=document.createElement('div');row.className='msg '+role; if(role==='assistant'){const img=document.createElement('img');img.src='blupi.jpg';img.className='mini-avatar';row.appendChild(img)} const b=document.createElement('div');b.className='bubble';b.textContent=text;row.appendChild(b);messages.appendChild(row);messages.scrollTop=messages.scrollHeight}
function render(){options.innerHTML=''; if(step<questions.length){const q=questions[step];bubble('assistant',q.text);q.opts.forEach((o,i)=>{const b=document.createElement('button');b.className='option';b.textContent=o;b.onclick=()=>answer(q,o);options.appendChild(b)})}else result()}
function answer(q,o){answers[q.key]=o;bubble('user',o);step++;setTimeout(render,250)}
function score(){let s=Object.fromEntries(Object.keys(data).map(c=>[c,0])); if(answers.cloud==='Yes'){s.Canada+=4;s.Australia+=4;s['New Zealand']+=3;s.Norway+=3;s.Brazil+=1} if(answers.customer==='Yes'){s.Canada+=4;s.Australia+=4;s['New Zealand']+=3;s.Norway+=2;s.Brazil+=2} if(answers.english==='Yes'){['Canada','Australia','New Zealand'].forEach(c=>s[c]+=7)} if(answers.language==='Portuguese'||answers.language==='Both')s.Brazil+=5;if(answers.language==='Norwegian'||answers.language==='Both')s.Norway+=5;if(answers.family==='Yes'){s.Canada+=5;s.Australia+=5;s['New Zealand']+=5;s.Norway+=5;s.Brazil+=1} if(answers.securitySalary==='Security'){s.Brazil=-999;['Canada','Australia','New Zealand','Norway'].forEach(c=>s[c]+=(140-data[c].peace)/20)}else Object.keys(s).forEach(c=>s[c]+=data[c].w/2); if(answers.salaryJobs==='Excellent salary'){s.Norway+=100}else Object.keys(s).forEach(c=>s[c]+=data[c].tech*30+data[c].cr*20+(1-data[c].u)*10); return s}
function result(){const s=score();let ranked=Object.entries(s).sort((a,b)=>b[1]-a[1]); if(answers.securitySalary==='Security')ranked=ranked.filter(x=>x[0]!=='Brazil'); if(answers.salaryJobs==='Excellent salary'){const n=ranked.find(x=>x[0]==='Norway');ranked=[n,...ranked.filter(x=>x[0]!=='Norway')]} ranked=ranked.slice(0,2); bubble('assistant','Thanks! 💛 I’ve stored your answers. Here are two destinations worth exploring:'); const r=document.createElement('div');r.className='result';r.innerHTML='<h2>Your Two Possible Destinations</h2><p>Based on your profile, preferences and the 2026 labor-market snapshot.</p>';ranked.forEach((x,i)=>{const c=x[0],why=[];if(answers.english==='Yes'&&['Canada','Australia','New Zealand'].includes(c))why.push('English-speaking destination');if(answers.cloud==='Yes')why.push('Cloud/Tech fit');if(answers.customer==='Yes')why.push('Customer Relations fit');if(c==='Norway'&&answers.salaryJobs==='Excellent salary')why.push('excellent-salary priority');if(answers.securitySalary==='Security')why.push('security priority');const d=document.createElement('div');d.className='country';d.innerHTML=`<strong>${i?'🥈':'🥇'} ${c}</strong><br><span>${why.slice(0,3).join(' • ')||'Selected from labor-market signals'}</span>`;r.appendChild(d)});messages.appendChild(r);const rb=document.createElement('button');rb.className='restart';rb.textContent='↻ Start again';rb.onclick=()=>{step=0;answers={};messages.innerHTML='';options.innerHTML='';bubble('assistant','Hi! 👋 I’m Blupi, your virtual assistant for career migration.');render()};messages.appendChild(rb);options.innerHTML=''}
bubble('assistant','Hi! 👋 I’m Blupi, your virtual assistant for career migration.');render();
